### ISSUE TITLE
I need a GDAL AAR Library

### ISSUE THREAD

**Issue by geochenyj** [paamand/GDAL#11]
Hello, can you provide me with a compiled 64-bit GDAL AAR library? thank you！

**Comment by paamand** [comment]
Sure:
[https://drive.google.com/file/d/12QxVhl3CJiHFSy6SKMZmY5d2HLDxtbea/view?usp=sharing](url)

If you feel like this saved you a ton of work consider contributing a share of your time to this or similar projects, or send a donation to your favorite charity.
[https://wikimediafoundation.org/support/](url)
