### ISSUE TITLE
Cannot find source file While build Android Studio project

### ISSUE THREAD

**Issue by EdYao** [paamand/GDAL#12]
As the title said, here is the log info:

CMake Error at CMakeLists.txt:8 (add_library):
  Cannot find source file:

    src/main/cpp/gdal_wrap.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

And I checked the directory, the src/main only contains one file AndroidManifest.xml.

**Comment by paamand** [comment]
Please read the readme and run the install script...
It compiles the dependencies and copies the headers to the relevant folders.

tir. 7. maj 2019 08.38 skrev EdYao <notifications@github.com>:

**Comment by EdYao** [comment]
@paamand Thanks for the reply. The install script cannot be run correctly, here is the log:


checking for aarch64-linux-android-gcc... /Users/bigemap/Desktop/BigeMap/AndroidNDK/android-ndk-r19c/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android19-clang
checking whether the C compiler works... no
configure: error: in `/Users/bigemap/Desktop/BigeMap/Test/GDAL/submodules/proj4':
configure: error: C compiler cannot create executables
See `config.log' for more details
make: *** No rule to make target `clean'.  Stop.
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target `install'.  Stop.
cp: /Users/bigemap/Desktop/BigeMap/Test/GDAL/submodules/../submodules/build/arm64-v8a/lib/libproj.so: No such file or directory
mkdir: /Users/bigemap/Desktop/BigeMap/Test/GDAL/submodules/src/main/cpp: File exists
cp: /Users/bigemap/Desktop/BigeMap/Test/GDAL/submodules/../submodules/build/arm64-v8a/include: No such file or directory
mkdir: /Users/bigemap/Desktop/BigeMap/Test/GDAL/submodules/libs: File exists
cp: gdal.jar: No such file or directory
cp: *_wrap.cpp: No such file or directory
cp: *_wrap.c: No such file or directory

I googled those errors, but cannot solve the error:(

**Comment by paamand** [comment]
1. Please specify your OS and NDK versions.
2. How did you invoke the script? E.g. did you provide the NDK dir and API number?

**Comment by EdYao** [comment]
@paamand  On macOS, using android-ndk-r19c;
I changed the install.sh by Subline Text,:
`export NDK_ROOT=/Users/bigemap/Desktop/BigeMap/AndroidNDK/android-ndk-r19c `
`export MIN_SDK_VERSION=19`
 And I cd to submodules/, and drag install.sh into terminal, then press enter....

**Comment by paamand** [comment]
The Readme states `Open a terminal and navigate to the project folder, e.g. ~/GDAL/gdal`.
This is because the script needs the project folder in order to properly copy files into the project.
E.g. 
`cd /Users/bigemap/Desktop/BigeMap/Test/GDAL/gdal`
`./../submodules/install.sh /Users/bigemap/Desktop/BigeMap/AndroidNDK/android-ndk-r19c 21`

**Comment by EdYao** [comment]
@paamand I redownload the whole repo by `git clone --recurse-submodules https://github.com/paamand/GDAL.git,`and make sure the directory is the same as the 
`cd /Users/bigemap/Desktop/BigeMap/Test/GDAL/gdal`
and then run 
`./../submodules/install.sh /Users/bigemap/Desktop/BigeMap/AndroidNDK/android-ndk-r19c 21`
 But the error still looks like the same :

rm: swig/java/apps/GDALtest.java: No such file or directory
#########  x86 : i686-linux-android  ##########
GNUmakefile:1: GDALmake.opt: No such file or directory
./config.status --recheck
make: ./config.status: No such file or directory
make: *** [config.status] Error 1
checking build system type... x86_64-apple-darwin18.5.0
checking host system type... i686-pc-linux-android
checking for i686-linux-android-gcc... /Users/bigemap/Desktop/BigeMap/AndroidNDK/android-ndk-r19c/toolchains/llvm/prebuilt/linux-x86_64/bin/i686-linux-android21-clang
checking whether the C compiler works... no
configure: error: in `/Users/bigemap/Desktop/BigeMap/Test/GDAL/submodules/gdal/gdal':
configure: error: C compiler cannot create executables
See `config.log' for more details

**Comment by paamand** [comment]
As the error states the NDK compiler is not found (or working). Is there a reason that you have a standalone NDK and not using the Android Studio NDK?
Also, I assume that you have autoconf and automake installed (not default on OSX).

**Comment by EdYao** [comment]
@paamand I downloaded the latest stable release NDK from [here](https://developer.android.com/ndk/downloads), should I configure it to the Android Studio? or should I download NDK by Android Studio? And yes I installed autoconf and automake , because I used to run install.sh and see some error, googled the error and installed autoconf and automake .

**Comment by EdYao** [comment]
@paamand I checked the Project Structure in Android Studio and find out the Android NDK location was not empty now(which was empty before, don't know which operation changed this circumstance), and the value is `/Users/bigemap/Library/Android/sdk/ndk-bundle `, whitch lied in the SDK directory. so I changed the install argument and rerun:
`./../submodules/install.sh /Users/bigemap/Library/Android/sdk/ndk-bundle 21 `

Turns out to see the same errors as before.

rm: swig/java/apps/GDALtest.java: No such file or directory
#########  x86 : i686-linux-android  ##########
GNUmakefile:1: GDALmake.opt: No such file or directory
./config.status --recheck
make: ./config.status: No such file or directory
make: *** [config.status] Error 1
checking build system type... x86_64-apple-darwin18.5.0
checking host system type... i686-pc-linux-android
checking for i686-linux-android-gcc... /Users/bigemap/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/i686-linux-android21-clang
checking whether the C compiler works... no
configure: error: in `/Users/bigemap/Desktop/BigeMap/Test/GDAL/submodules/gdal/gdal':
configure: error: C compiler cannot create executables
See `config.log' for more details

**Comment by paamand** [comment]
Either way should be ok. I don't know why it fails to see the NDK compiler. Please check that the compiler is actually there (e.g. do you have the file `/Users/bigemap/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/i686-linux-android21-clang`?
One bet could be that the NDK somehow does not have the prebuild toolchains and that you must make them 'standalone'.

**Comment by kwatee** [comment]
On line #5 of install.sh, HOST_TAG is hardcoded to linux-x86_64 which makes the build fail on MacOS.
Changing it to darwin-x86_64, or alternatively creating a symbolic link from linux-x86_64 to darwin-x86_64 fixes the issue

**Comment by kwatee** [comment]
On MacOS there is also a failure on swig which is not pre-installed. You can get it from brew
