### ISSUE TITLE
Task :gdaltest:compileDebugJavaWithJavac FAILED

### ISSUE THREAD

**Issue by GrayCygnus** [paamand/GDAL#14]
I successfully ran `./gradlew installFromSource`.

Now I am attempting to run `./gradlew build` but it quickly fails, and indicates the following trace:

>/home/graycygnus/gdalAndroidAARTest/GDAL/gdaltest/src/main/java/eu/paamand/gdaltest/MainActivity.java:7: error: package org.gdal.gdal does not exist
import org.gdal.gdal.gdal;
                    ^
/home/graycygnus/gdalAndroidAARTest/GDAL/gdaltest/src/main/java/eu/paamand/gdaltest/MainActivity.java:8: error: package org.gdal.osr does not exist
import org.gdal.osr.CoordinateTransformation;
                   ^
/home/graycygnus/gdalAndroidAARTest/GDAL/gdaltest/src/main/java/eu/paamand/gdaltest/MainActivity.java:9: error: package org.gdal.osr does not exist
import org.gdal.osr.SpatialReference;
                   ^
/home/graycygnus/gdalAndroidAARTest/GDAL/gdaltest/src/main/java/eu/paamand/gdaltest/MainActivity.java:10: error: package org.gdal.osr does not exist
import org.gdal.osr.osr;
                   ^
/home/graycygnus/gdalAndroidAARTest/GDAL/gdaltest/src/main/java/eu/paamand/gdaltest/MainActivity.java:19: error: cannot find symbol
        String versionNfo = gdal.VersionInfo();
                            ^
  symbol:   variable gdal
  location: class MainActivity
/home/graycygnus/gdalAndroidAARTest/GDAL/gdaltest/src/main/java/eu/paamand/gdaltest/MainActivity.java:33: error: cannot find symbol
        SpatialReference utmSpatialReference = new SpatialReference();
        ^
  symbol:   class SpatialReference
  location: class MainActivity
/home/graycygnus/gdalAndroidAARTest/GDAL/gdaltest/src/main/java/eu/paamand/gdaltest/MainActivity.java:33: error: cannot find symbol
        SpatialReference utmSpatialReference = new SpatialReference();
                                                   ^
  symbol:   class SpatialReference
  location: class MainActivity
/home/graycygnus/gdalAndroidAARTest/GDAL/gdaltest/src/main/java/eu/paamand/gdaltest/MainActivity.java:35: error: cannot find symbol
        CoordinateTransformation trsform = osr.CreateCoordinateTransformation(
        ^
  symbol:   class CoordinateTransformation
  location: class MainActivity
/home/graycygnus/gdalAndroidAARTest/GDAL/gdaltest/src/main/java/eu/paamand/gdaltest/MainActivity.java:36: error: cannot find symbol
                new SpatialReference(EPSG4326), //LatLng
                    ^
  symbol:   class SpatialReference
  location: class MainActivity
/home/graycygnus/gdalAndroidAARTest/GDAL/gdaltest/src/main/java/eu/paamand/gdaltest/MainActivity.java:35: error: cannot find symbol
        CoordinateTransformation trsform = osr.CreateCoordinateTransformation(
                                           ^
  symbol:   variable osr
  location: class MainActivity
10 errors

Up untill now everything has been smoothly, so I don't know if I'm missing some step or missing a file or something. If more details are needed, I'll gladly provide them :)

**Comment by paamand** [comment]
Can you tell us your os and ndk/sdk version?
The install script should have build the libs and copied the relevant
headers into the project. Can you show your project file structure and
confirm that the relevant files are there?

//Rune

fre. 19. jul. 2019 00.17 skrev Miguel <notifications@github.com>:

**Comment by GrayCygnus** [comment]
I'm on Ubuntu 16.04
NDK v. 19.1.5304403
SDK Android 9.0 (Pie) (also got 8.1 installed)

Don't know what you mean exactly by the relevant files (several files were created), but here is the project structure right now:

    GDAL/
        gdal/
          build/
             generated/
                res/
                   pngs/
                      debug/ (empty)
                      install/ (empty)
                   resValues/
                      debug/ (empty)
                      install/ (empty)
                source/
                        apt/
                            debug/ (empty)
                            install/ (empty)
                        buildConfig/
                            debug/
                                ...eu.paamand.gdal.BuildConfig.java
                            install/
                                 ...eu.paamand.gdal.BuildConfig.java
                            release/
                                 ...eu.paamand.gdal.BuildConfig.java
                intermediates/
                    (several folders, like javac/, incremental/, annotations_zip/, lint_jar/...)
                outputs/
                    logs/
                        manifest-merger-debug-report.txt
                        manifest-merger-install-report.txt
                tmp/
                    compileDebugJavaWithJavac/ (empty)
                    compileInstallJavaWithJavac/ (empty)
            libs/
                gdal.jar
            src/
                ...(the main folder, cpp files, jniLibs, etc.)
        gdaltest/
            
        gradle/
            wrapper/
                gradle-wrapper.jar
                gradle-wrapper.properties
        submodules/
            build/
                arm64-v8a/
                armeabi-v7a/
                x86/
                x86_64/
                (each with bin/, etc/, include/, lib/, share/ and files within)
            gdal/
                autotest/
                    (several folders and files, ogr, osr, ruby, gcore, etc.)
                gdal/
                    (several folders and files, ogr, scripts, swig, alg, etc.)
                (other files, yml, md)
            proj4/
                (several folders and files, src, scripts, jniwrap, etc.)
            install.sh

**Comment by paamand** [comment]
Did you build the `gdal` project? It seems that you are building the `gdaltest` example but the dependencies are missing. You must first build the .aar files with the `gdal` project before the gdaltest can be build.
E.g. the `gdaltest/build.gradle` has the dependency `implementation fileTree(include: ['*debug.aar'], dir: '../gdal/build/outputs/aar')`

**Comment by GrayCygnus** [comment]
I am following the instructions specified [here](https://github.com/paamand/GDAL4Android/blob/master/README.md#if-building-in-android-studio-fails) exactly step by step (I noticed that those instructions and the ones on this repo's readme are a *bit* different, perhaps that could be the issue?):

>If building in Android Studio fails
>- Open a terminal
     - Navigate to this repository (i.e., `cd ~/GDAL`)
     - Set these environment variables:
         - `JAVA_HOME=[Embedded JDK location] && export JAVA_HOME`
         - `ANDROID_HOME=[Android SDK location] && export ANDROID_HOME`
     - Run `./gradlew installFromSource`
         - This calls ./submodules/install.sh that creates standalone toolchains and cross-compiles the actual GDAL and PROJ.4 submodules. The compiled libraries are moved to relevant folders along with the wrapper headers etc:
         - If this fails, navigate to `GDAL/gdal` and enter the following:
             - `../submodules/install.sh "[Android NDK location]" "19" 2>&1 | tee gdal-install.log`
                 - If this also fails, please share the log file
             - The NDK location is usually $ANDROID_HOME/ndk-bundle
                - If not, it can be found in the `GDAL/local.properties` file
     - Run `./gradlew build`
         - This should produce the gdal-release.aar and gdal-debug.aar files in `GDAL/gdal/build/outputs/aar/`
>The .aar files (gdal-release.aar and gdal-debug.aar) are self-contained with arm-v7s/x86 compiled libs and java wrappers and can be used directly on other projects. Clean AF.

I see that this repo's readme is more recent, and that on the edit history you removed the `./gradlew installFromSource` part... I'll try again following the most recent readme (that is, without the `installFromSource` but with manually running the install script).

**Comment by GrayCygnus** [comment]
Hey @paamand I followed your Readme and was able to successfully build the gdal! Now, the gdaltest also builds correctly :)

Thanks for the support, seems that indeed the `installFromSource` part should not be run (as suggested in the other repo that branched this one).

One thing, I noticed an instruction that is a bit ambiguous:

>- Navigate to `~/GDAL/gdal` folder and enter the following:
             - `./../submodules/install.sh "[Android NDK location]" "21" 2>&1 | tee gdal-install.log`
                 - If this also fails, please share the log file
             - The NDK location is usually $ANDROID_HOME/ndk-bundle or `~/Android/Sdk/ndk-bundle 21` (OS dependent)
                - If not, it can be found in the `GDAL/local.properties` file
>- Run `./gradlew build`
         - This should produce the gdal-release.aar and gdal-debug.aar files in `GDAL/gdal/build/outputs/aar/`

You indicate one has to navigate to /GDAL/gdal and run `install.sh`, and then indicate to run `./gradlew build`. However, one has to run `../gradlew build` as in the /GDAL/gdal/ folder there is no gradlew executable.

Thanks for the help :)
