### ISSUE TITLE
GDAL Drivers not found.

### ISSUE THREAD

**Issue by RobertsR** [paamand/GDAL#15]
I am trying to create a shapefile. But when I do 

> Driver driver = ogr.GetDriverByName("ESRI Shapefile");

It return null. Then I tried 

> gdal.GetDriverCount()

And it returns 0.
How to include ESRI Shapefile driver?

**Comment by paamand** [comment]
I honestly have no idea.
Are you able to use the same code on a Unix build of GDAL? And if so, what
build options do you use?
//R

lør. 20. jul. 2019 14.35 skrev RobertsR <notifications@github.com>:

**Comment by RobertsR** [comment]
I tried .aar I created and the one you posted in one of these posts. Can't seem to get it running anywhere. 
Could you check this code?

> public void GDALTestt(){
>         //Create ring
>         Geometry ring = new Geometry(ogr.wkbLinearRing);
>         ((Geometry) ring).AddPoint(1179091.1646903288, 712782.8838459781);
>         ((Geometry) ring).AddPoint(1161053.0218226474, 667456.2684348812);
>         ((Geometry) ring).AddPoint(1214704.933941905, 641092.8288590391);
>         ((Geometry) ring).AddPoint(1228580.428455506, 682719.3123998424);
>         ((Geometry) ring).AddPoint(1218405.0658121984, 721108.1805541387);
>         ((Geometry) ring).AddPoint(1179091.1646903288, 712782.8838459781);
> 
>         //Create polygon
>         Geometry poly2 = new Geometry(ogr.wkbPolygon);
>         poly2.AddGeometry(ring);
>         
>         // Here's an example Shapely geometry
>         Geometry poly = new Geometry(ogr.wkbPolygon);
>         poly.AddGeometry(ring);
>         //Geometry poly = ogr.wkbPolygon(ring);
> 
>         // Now convert it to a shapefile with OGR
>         Log.d("GetDriverCount", "" + gdal.GetDriverCount());
>         Driver driver = ogr.GetDriverByName("ESRI Shapefile");
>         String path = this.getFilesDir() + "/my.shp";
>         DataSource ds = driver.CreateDataSource(path);
>         Layer layer = ds.CreateLayer("", null, ogr.wkbPolygon);
>         // Add one attribute
>         layer.CreateField(new FieldDefn("id", ogr.OFTInteger));
>         FeatureDefn defn = layer.GetLayerDefn();
> 
>         //If there are multiple geometries, put the "for" loop here
> 
>         //Create a new feature (attribute and geometry)
>         Feature feat = new Feature(defn);
>         feat.SetField("id", 123);
> 
>         //Make a geometry, from Shapely object
>         Geometry geom = ogr.CreateGeometryFromWkb(poly.ExportToWkb());
>         feat.SetGeometry(geom);
> 
>         layer.CreateFeature(feat);
>     }

**Comment by RobertsR** [comment]
Have you tested drivers? If yes, maybe you could share your .aar?

Does it matter that I used UNIX only to build .aar and then got back to Windows?

**Comment by paamand** [comment]
I have not particularly tested drivers. My own use of the library is centered around PNG/JPEG files, and those work well. I will try to reproduce your example.

It should not matter if you compile it on UNIX as it is cross-compiled to android. You are not running it on Windows, right? There are a few working .aar files in this thread:
[https://github.com/paamand/GDAL4Android/issues/8](https://github.com/paamand/GDAL4Android/issues/8)

My question was: Are you able to do your operations on a NON-ANDROID system - and if so, which binaries compiled in what way? If there are specific compile-options to include then that could be the answer.

**Comment by RobertsR** [comment]
I am running Windows to develop application on Android Studio.

What do you mean by non-android system? You mean to create a new project like python? Should I use this .aar or downloaded from GDAL website? Where to find compile-options?
Im not that familiar with UNIX systems. I was using it just to get this .aar. 

I have added this line to build.gradle file

> implementation fileTree(include: ['*gdal-release_API21.aar'], dir: 'libs')

And copied .aar file into libs folder. Do I need to do anything else?

**Comment by paamand** [comment]
What I am trying to say is
1: Android requires arch-specific binaries compatible with the android
hardware.
2: When you *cross* compile you are compiling for that specific hardware
(in various variants).
3: This means that it will not matter if the *.aar file was compiled with
unix, windows or other. But I only 'support' unix since some tools were
only available there.
4: A *.aar file is just a fancy packaging of the binary libraries. You can
use the one is the thread that I linked to.
5: I have not seen your problem before and wonder if it is specific for
android or general for GDAL?

Hope this helps.

**Comment by RobertsR** [comment]
Turns out I had to do 

> ogr.RegisterAll();

Before I started doing anything with drivers.

Thanks for help!
