### ISSUE TITLE
Can you provide TWO AAR FILES for debug and release，please? 

### ISSUE THREAD

**Issue by NightMoonCat** [paamand/GDAL#18]

**Comment by NightMoonCat** [comment]
By the way, it would be better to have GDAL 3.2.0 VERSION.
(〃'▽'〃)   (〃'▽'〃)  (〃'▽'〃)

**Comment by paamand** [comment]
Thanks for the suggestion.
Have you tried amending the build scripts in any way?
I will take a look when time allows.

**Comment by NightMoonCat** [comment]
Your code worked well in LINUX,and I got two AAR files.
Thanks!
Now,I am going to try GDAL3.2.0.

**Comment by vTechGIS** [comment]
@NightMoonCat , Hello, Could you share the results after trying GDAL 3.2.0. I have failed to upgrade to GDAL 3.2.0 :(
Thanks you,

**Comment by NightMoonCat** [comment]
> @NightMoonCat , Hello, Could you share the results after trying GDAL 3.2.0. I have failed to upgrade to GDAL 3.2.0 :(
> Thanks you,

emmm.In fact, I also failed with GDAL 3.2.0.
Finally,I used GDAL2.4.4.But it has garbled characters in Chinese.

**Comment by paamand** [comment]
I may be able to upgrade GDAL, but PROJ4 has a new dependency on SQLite3 which is hard to satisfy in cross-compilation. Will think of redefining the project to GDAL only and abandon PROJ4 for now...
