### ISSUE TITLE
gradlew build failed: Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by GrayCygnus** [paamand/GDAL#6]
After some time I manager to successfully run `./gradlew installFromSource` following the instructions explained on the README to the letter.

Now, I am attempting to build it using `./gradlew build`, for which I encountered some issues. First, I found that I had to run that command with `sudo`. After that, it proceeded normally until it threw an error that reads:

>FAILURE: Build failed with an exception.
>* Where:
>Build file '/home/graycygnus/AndroidStudioProjects/GDAL/gdal/build.gradle' line: 1
>* What went wrong:
>A problem occurred evaluating project ':gdal'.
>\> java.lang.UnsupportedClassVersionError: com/android/build/gradle/LibraryPlugin : Unsupported major.minor version 52.0

Digging around StackOverflow and other places, I found that such error is thrown when you attempt to run with an older JRE. The solution most commonly found is to install Java8 and use it to run the build (setting the JAVA_HOME to the newer java8). 

However, I am on Ubuntu 14.04 LTS, so getting Java 8 is not so trivial (it seems that for 14.04 you have to get it from an alternative ppa repo, and get the Oracle version as well)... 

So... before I attempt to install and get Java 8 and try building with it, **I want to ask if you see something that perhaps I'm missing, or that you suggest I try before going for the install Java8 option?**

Some info (if more is needed, I'll provide it gladly):

Ubuntu 14.04
When selection `Help > About` I get:

>Android Studio 3.3.1
Build #AI-182.5107.16.33.5264788, built on January 28, 2019
JRE: 1.8.0_152-release-1248-b01 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.4.0-137-generic

I am curious about the "JRE: 1.8.0" as it would suggest that it already uses Java8. But, then why complain for `UnsupportedClassVersion` when I run `./gradlew build` on my terminal? Perhaps the issue has something to do with that? I have selected the "use embedded JDK" which path is `/opt/android-studio/jre`, and therefore my JAVA_HOME is set to that path.

**Comment by GrayCygnus** [comment]
*Update:* Seems that prior to running `./gradlew installFromSource` the latest SDK Platform I had installed was Android 8.1 (Oreo), which is not the latest, 9.0 (Pie)... 

Could this be the cause of the issue? I.e.: should I start again and `installFromSource` after downloading and installing Android 9.0?

**Comment by paamand** [comment]
It could be an issue. The `installFromSource` will compile with a
standalone toolchain that is specific to the API version:
https://developer.android.com/ndk/guides/standalone_toolchain#selecting_your_sysroot


//R

**Comment by GrayCygnus** [comment]
Ok, @paamand  thanks. I will proceed to install again after getting the Pie SDK, and update any progress here when I get it. Thanks for the fast reply! :)

**Comment by GrayCygnus** [comment]
@paamand I just did the process again, after installing the Android Pie SDK. I successfully ran `installFromSource`, but reached the same error again as detailed in the Issue... any thoughts given this new info?

**Comment by paamand** [comment]
Did you try these steps:
https://stackoverflow.com/questions/22489398/unsupported-major-minor-version-52-0

> These are the assigned major numbers. The error regarding the unsupported major.minor version is because during compile time you are using a higher JDK and a lower JDK during runtime.

I expect that this is not an issue with the library.

**Comment by GrayCygnus** [comment]
Yes, I tried those steps unsuccessfully (that post and others were the ones I checked out, as mentioned in my initial comment). I'll keep trying options and post here if I solve it
