### ISSUE TITLE
gdal.Open must not be null for Geospatial PDFs

### ISSUE THREAD

**Issue by jfacoustic** [paamand/GDAL#9]
```kotlin
gdal.AllRegister()
val test = gdal.Open("/something.pdf")
```

returns null, which crashes my program.

Opening a GeoTiff works perfectly and `gdal.GDALInfo(test, null)` returns a string with the correct information.  

This is because the default compilation does not support PDFs.  [You have to add either Poppler, PDFium, or PoDoFo as a dependency.](https://www.gdal.org/frmt_pdf.html) 

I tried adding Poppler as a compile flag in the submodules/install.sh, but it still gave the `gdal.GDALOpen() must not be null` error for pdfs.  

Line 18 of install.sh:
```sh
CC="arm-linux-androideabi-clang" CXX="arm-linux-androideabi-clang++" CFLAGS="-mthumb" CXXFLAGS="-mthumb" LIBS="-lstdc++" ./configure --host=arm-linux-androideabi --with-libz=internal --prefix=$BUILDDIR/arm --with-threads --with-poppler
```

When I [compiled GDAL for desktop Unix](https://trac.osgeo.org/gdal/wiki/BuildingOnUnix) including the `--with-poppler` flag, it could read the same PDF without any problems and GDALInfo returned the correct data.

**Comment by paamand** [comment]
Thanks for the detailed report.
Compiling on your unix system using the `--with-` flags uses your system-version of the given libraries. No such library is included for Android.

You are more than welcome to try and cross-compile the PDF libs for Android and include them. It should be sufficient to link to precompiled libs with the `--with-lib=path/to/lib` flags.

This is not an issue with this project as such. It is more like an extension of the *core* GDAL.
Notice likewise that the xml2 and curl libraries have been explicitly omitted in the latest commit for 64-bit support.

**Comment by GrayCygnus** [comment]
@jfacoustic did you manage to be able to open PDFs on Android, or to cross-compile the libs to Android? If so, would you be so kind to tell us how? :)
